version: '3.3'
services:
    laravel-docker:
        build: ./
        ports:
            - '9002:80'
        volumes:
            - './:/usr/share/nginx/html'
        restart: always
        depends_on:
            - db
        networks:
            - docker
    db:
        image: mysql
        restart: always
        ports:
            - '3308:3306'
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: superlogica
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - '.docker/dbdata:/var/lib/mysql'
        networks:
            - docker

networks:
    docker:
        driver: bridge
